version: '2'

services: 
  feishu:
    image: u03013112/feishu:v1
    container_name: 'feishu'
    tty: true
    command: python /src/rpycServer.py
    volumes:
        - ../feishu:/src
    ports:
      - 10001:12345
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
  
  gpt:
    image: u03013112/gpt:v1
    container_name: 'gpt'
    tty: true
    command: python /src/rpycServer.py
    volumes:
        - ../gpt:/src
    ports:
      - 10002:12345
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
  